[build]
  # 发布目录
  publish = "."
  
  # 构建命令（纯前端项目不需要构建）
  command = "echo 'No build required for static site'"

[build.environment]
  # Node.js版本（如果需要）
  NODE_VERSION = "18"

# 重定向规则 - 修复：只对HTML页面进行重定向，不影响静态资源
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 缓存控制
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    # HTML文件不缓存
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    # JavaScript文件缓存1年
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # CSS文件缓存1年
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    # 图片文件缓存1年
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    # 图片文件缓存1年
    Cache-Control = "public, max-age=31536000, immutable"

# 表单处理（如果将来需要）
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
# [build.processing.html]
#   pretty_urls = true

# 插件配置
# [[plugins]]
#   package = "netlify-plugin-lighthouse"

# 开发环境设置
[dev]
  command = "python -m http.server 8000"
  port = 8000
  publish = "."
  autoLaunch = true